sudo: require

env:
  - RUBY_IMAGE=2.6
  - RUBY_IMAGE=2.7

services:
  - docker

install:
  - gem install dip

before_script:
  - unset BUNDLE_GEMFILE
  - dip provision

script:
  - dip rubocop
  - dip appraisal rspec
